-- defines dub rules for xmake

-- build option rules
-- see https://github.com/dlang/dub/tree/master/source/dub/compilers
-- and https://github.com/dlang/dub/blob/master/source/dub/compilers/buildsettings.d

rule("dub.options.debugMode")
    on_config(function (target)
        import("utils")(target, "-fdebug", "-d-debug", "-debug")
    end)
rule_end()

rule("dub.options.releaseMode")
    on_config(function (target)
        import("utils")(target, "-frelease", "-release", "-release")
    end)
rule_end()

rule("dub.options.coverage")
    on_config(function (target)
        import("utils")
        flag(target, "", "-cov", "-cov")
        gdc_flag("-fprofile-arcs")
        gdc_flag("-ftest-coverage")
    end)
rule_end()

rule("dub.options.debugInfo")
    on_config(function (target)
        import("utils")(target, "-g", "-g", "-g")
    end)
rule_end()

rule("dub.options.debugInfoC")
    on_config(function (target)
        import("utils")
        flag(target, "", "-gc", "-gc")
        gdc_flag(target, "-g", "-fdebug-c")
    end)
rule_end()

rule("dub.options.alwaysStackFrame")
    on_config(function (target)
        import("utils")
        flag(target, "", "-disable-fp-elim", "-gs")
    end)
rule_end()

rule("dub.options.stackStomping")
    on_config(function (target)
        import("utils")
        dmd_flag(target, "-gx")
    end)
rule_end()

rule("dub.options.inline")
    on_config(function (target)
        import("utils")(target, "-finline-functions", "-enable-inlining", "-inline")
    end)
rule_end()

rule("dub.options.noBoundsCheck")
    on_config(function (target)
        import("utils")(target, "-fno-bounds-check", "-disable-boundscheck", "-noboundscheck")
    end)
rule_end()

rule("dub.options.optimize")
    on_config(function (target)
        import("utils")(target, "-O3", "-O", "-O")
    end)
rule_end()

rule("dub.options.profile")
    on_config(function (target)
        import("utils")(target, "-pg", "-fdmd-trace-functions", "-profile")
    end)
rule_end()

rule("dub.options.unittests")
    on_config(function (target)
        import("utils")(target, "-funittest", "-unittest", "-unittest")
    end)
rule_end()

rule("dub.options.verbose")
    on_config(function (target)
        import("utils")(target, "-fd-verbose", "-v", "-v")
    end)
rule_end()

rule("dub.options.ignoreUnknownPargmas")
    on_config(function (target)
        import("utils")(target, "-fignore-unknown-pragmas", "-ignore", "-ignore")
    end)
rule_end()

rule("dub.options.syntaxOnly")
    on_config(function (target)
        import("utils")(target, "-fsyntax-only", "-o-", "-o-")
    end)
rule_end()

rule("dub.options.warnings")
    on_config(function (target)
        import("utils")(target, "-Wall", "-wi", "-wi")
    end)
rule_end()

rule("dub.options.warningsAsErrors")
    on_config(function (target)
        import("utils")
        flag(target, "", "-w", "-w")
        gdc_flag(target, "-Werror")
        gdc_flag(target, "-Wall")
    end)
rule_end()

rule("dub.options.ignoreDeprecations")
    on_config(function (target)
        import("utils")(target, "-Wno-deprecated", "-d", "-d")
    end)
rule_end()

rule("dub.options.deprecationWarnings")
    on_config(function (target)
        import("utils")(target, "-Wdeprecated", "-dw", "dw")
    end)
rule_end()

rule("dub.options.deprecationErrors")
    on_config(function (target)
        import("utils")
        flag(target, "", "-de", "-de")
        gdc_flag(target, "-Werror")
        gdc_flag(target, "-Wdeprecated")
    end)
rule_end()

rule("dub.options.property")
    on_config(function (target)
        import("utils")(target, "-fproperty", "-property", "-property")
    end)
rule_end()

rule("dub.options.profileGC")
    on_config(function (target)
        import("utils")
        dmd_flag(target, "-profile=gc")
    end)
rule_end()

rule("dub.options.pic")
    -- empty
rule_end()

rule("dub.options.betterC")
    on_config(function (target)
        import("utils")("-fno-druntime", "-betterC", "-betterC")
    end)
rule_end()

rule("dub.options.lowmem")
    on_config(function (target)
        import("utils")("", "-lowmem", "-lowmem")
    end)
rule_end()

rule("dub.options.coverageCTFE")
    on_config(function (target)
        import("utils")("", "-cov=ctfe", "-cov=ctfe")
    end)
rule_end()

rule("dub.options.color")
    on_config(function (target)
        import("utils")("-fdiagnostics-color=always", "-enable-color", "-color")
    end)
rule_end()
